#!/usr/bin/env bash
# This script shall transfer file from client to server
# and it shall accept 4 param

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi
