#!/usr/bin/env bash
# This script shall install nginx on server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
