#!/usr/bin/env bash
# This script shall install nginx on server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 80
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
