#!/usr/bin/env bash
# This script shall install nginx on server
# this shall return 301 code when redirected to page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 80
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default 
sudo service nginx restart
