#!/usr/bin/env bash
# This script shall install nginx on server
# this shall return 301 code when redirected to page
# and return a custom 404 page when page not found
# also return a custom HTTP header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 80
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/my_404.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/server.name..;/a \        error_page 404 /my_404.html;\n   location = /my_404.html {\n              root /var/www/html;\n           internal;\n     }'  /etc/nginx/sites-enabled/default
sudo sed -i "17i \\\tadd_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx restart
