#!/usr/bin/env bash
# THis script shall install load balancer and conf haproxy

sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy

echo "
frontend Load_balancer
    bind *:80
    mode http
    default_backend Web_Server

backend Web_Server
    mode http
    balance roundrobin
    server 503273-web-01  54.174.72.190:80 check
    server 503273-web-02  54.174.125.226:80 check
" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
