#!/usr/bin/env bash
# This script shall do a loop with a sleep 2 and sigterm quo whn sigterm sig

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM
done
