#!/usr/bin/env bash
# This script shall print bad luck 4 and good luck 8 and best school for other

x=1
while [ $x -le 10 ]
do
  if [ $x -eq 4 ]
  then
    echo "bad luck"
  elif [ $x -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((x++))
done
