#!/usr/bin/env bash
#This script shall displays num from 1 to 20 with prnt bd lck

x=1
while [ $x -le 20 ]
do
  case $x in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;	
    *)
      echo "$x"
      ;;
    esac
    ((x++))
done
