#!/usr/bin/env bash
# This script shall give info about school file exist ,empty and regular or not

FILE="school"
if [ -e "$FILE" ]
then
  echo "$FILE file exists"
  if [ -s "$FILE" ]
  then
    echo "$FILE file is not empty"
  else
    echo "$FILE file is empty"
  fi
  if [ -f "$FILE" ]
  then
    echo "$FILE is a regular file"
  else
    echo "$FILE is not a regular file"
  fi
else
  echo "$FILE file does not exist"
fi
